---
title: SQL homework 2
author: Evan Mascitti
date: 2021-03-31
mainfont: Arial
linestretch: 1.15
highlight: tango
output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: sql-hw2-preamble.tex
---
```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F, comment = "")
knitr::opts_knit$set(root.dir = here::here('SQL', 'homework2'))

show_output <- function(x){
  cat(xfun::read_utf8(x), sep = "\n")
}
```

# Problem 1

## Part a)

### Code: 

```SQL
sqlite3

# some options 
.echo on
.trace
.header on
.mode column


# load .db file 
.open lohr_and_haag.db

# capture output for this command 
.once prob1a.txt

# query:
SELECT MIN(afr), MAX(afr), AVG(afr) FROM lohr_and_haag GROUP BY pop;

```

### Output: 

```{r prob1a}
show_output('prob1a.txt')
```


## Part b)

### Code: 

```SQL
.once prob1b.txt
SELECT pop, COUNT(pop) AS numInd FROM lohr_and_haag 
    WHERE ad > 55 GROUP BY pop;
```

### Output: 

```{r}
show_output('prob1b.txt')
```

# Problem 2

## Part a)

```SQL
# open database 
.open Mikaelyan_et_al_2015.db

# ouput schema 
.once prob2a.txt
.schema
```

```{r}
show_output('prob2a.txt')
```


## Part b)

### Code 

```SQL
.once prob2b.txt
SELECT Spp, OTU, Num FROM tNumber 
  INNER JOIN tOTU 
    ON tNumber."IDOTU" = tOTU."IDOTU" 
  INNER JOIN tSpp
    ON tNumber."IDSpp" = tSpp."IDSpp"
  LIMIT 10;
```

### Output 
```{r}
show_output('prob2b.txt')
```


## Part c)

```SQL
.once prob2c.txt
CREATE VIEW summary AS SELECT Spp, OTU, Num FROM tNumber 
  INNER JOIN tOTU 
    ON tNumber."IDOTU" = tOTU."IDOTU" 
  INNER JOIN tSpp
    ON tNumber."IDSpp" = tSpp."IDSpp";
```

## Part D)



